sudo: false

language: php

php:
  - 7.0
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: nightly

env:
  - PHP_WEAK_VERSION=master
  - PHP_WEAK_VERSION=v0.4.1

before_install:
   - sh install_php_ref_ext.sh ${PHP_WEAK_VERSION}
   - echo 'extension = ref.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/ref.ini

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
